version: '3.7'
services:
    app:
        build: build 
        ports:
            - "8888:8000"
        volumes:
            - ./mpapws:/var/www/html
        command: symfony serve 
    mysql:
        image: mysql
        ports:
            - 3307:3306
        volumes:
            - ./mysql:/var/lib/mysql:delegated
        environment:
            MYSQL_DATABASE: db-mpapws
            MYSQL_USER: mpapws
            MYSQL_PASSWORD: mpapws
            MYSQL_ROOT_PASSWORD: mpapws
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: "mpapws"
        restart: always
        ports:
            - 2000:80
        volumes:
            - /sessions

    mail:
        image: mailhog/mailhog
        ports:
            - 1080:8025

