version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: build 
        ports:
            - "8888:8000"
        volumes:
            - .:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: symfony
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"

volumes:
  db-data:
